### ISSUE TITLE
Example Output Problem

### ISSUE THREAD

**Issue by YuiAki** [MicrosoftDocs/cpp-docs.zh-cn#42]
There is an error on Example  Output part.For "string = -10110134932This stopped it",the output should be "strtol = -10110134932" but "strtol = -2147483648".

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0656f7f5-94a4-e2cd-c0ff-7949a271dd45
* Version Independent ID: 7f8311a0-098a-d03e-d215-61c00c88966e
* Content: [strtod、_strtod_l、wcstod、_wcstod_l](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l?view=vs-2017)
* Content Source: [docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-runtime-library/reference/strtod-strtod-l-wcstod-wcstod-l.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #558](https://github.com/MicrosoftDocs/cpp-docs/issues/558) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @YuiAki 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/558.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
